name: compile and release slides
on:
  push:
    branches:
      - main
      - master

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Build latex
        uses: xu-cheng/latex-action@v3
        with:
          root_file: curriculum_vitae.tex

      - name: Prepare assets
        run: |
          mkdir -p assets
          cp ./*.pdf ./assets/
